spring:
  application:
    name: ai-solution-voice
  servlet:
    session:
      timeout: 60m  # 60분
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
      platform: h2
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true           # ??? SQL ??
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true